welcome: Default welcome
spring:
  application:
    name: my-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/Dhurjad/Config.git
          default-label: main

server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: '*'
