welcome: Default welcome(V1)
spring:
  application:
    name: my-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/Dhurjad/Config.git
          #default-label: main

server:
  port: 8085
management:
  endpoints:
    web:
      exposure:
        include: '*'
